[project]
name = "when2meet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lux-maker", email = "socpopcap@proton.me" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "flask-sqlalchemy>=3.1.1",
    "werkzeug>=3.1.8",
    "gunicorn>=23.0.0",
]

[project.scripts]
when2meet = "when2meet:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
